export default {
    designWidth: 1920,
    designHeight: 1080,
    backgroundColor: 0x888888,
    fps: 60,
    gravity: 0,
    planeImagePath: "images/rocket.png",
    bgImagePath: "images/bg.png",
    pixel2meter: 0.0625,
    meter2pixel: 16,
    planeRadius: 2.65625,
    planeVelocity: 30,
    planeEngineForce: 10,
    planeAngleVelocity: Math.PI / 180 * 10,
    meteorImagePath: "images/meteorite.png",
    meteorRadius: 1.71875,
    meteorMinVelocity: 10,
    meteorMaxVelocity: 20,
    meteorMinCount: 1,
    meteorMaxCount: 2,
    meteorRestitution: 1,
    refreshMeteorProbability: 0.01,
    refreshMeteorMinCount: 0,
    refreshMeteorMaxCount: 1,
    meteorExistMaxCount: 20,
};