export default {
    designWidth: 1920,
    designHeight: 1080,
    backgroundColor: 0x888888,
    fps: 60,
    gravity: 0,
    planeImagePath: "images/rocket.png",
    bgImagePath: "images/bg.png",
    pixel2meter: 0.0625,
    meter2pixel: 16,
    planeRadius: 2.65625,
    planeVelocity: 30,
    planeEngineForce: 10,
    planeAngularVelocity: Math.PI / 180 * 5,
    meteorImagePath: "images/meteorite.png",
    meteorRadius: 1.71875,
    meteorMinVelocity: 10,
    meteorMaxVelocity: 20,
    meteorMinCount: 1,
    meteorMaxCount: 2,
    meteorRestitution: 1,
    meteorAngularVelocity: 5,
    refreshMeteorProbability: 0.01,
    refreshMeteorMinCount: 1,
    refreshMeteorMaxCount: 2,
    meteorExistMaxCount: 10,
    wormImagePath: "images/worm.png",
    wormAngularVelocity: Math.PI / 180 * 1,
    wormVelocity: 10,
    wormEngineForce: 5,
    wormMinCount: 1,
    wormMaxCount: 2,
    wormExistMaxCount: 2,
    refreshWormProbability: 0.1 ,
};